"use client";

// Floating, draggable robot assistant. Polls /api/ai-activity: while any
// Claude task is running server-side it plays a "working" animation, and
// when the last task finishes it says "Done!" for a few seconds.
//
// Also doubles as the site's help chat entry point: a plain click (as
// opposed to a drag) opens a fixed chat panel backed by /api/assistant (see
// src/lib/assistantChat.ts) that answers "how do I use this site" questions.
// For a user's very first authenticated page load after registering, it
// auto-opens with a scripted, locally-generated welcome tour of the site's
// main pages (see WELCOME_ZH/WELCOME_EN below) instead of waiting to be
// clicked — see the "first-run tour" effect further down.

import { useCallback, useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { useLocale } from "@/lib/i18n";

type Mood = "idle" | "working" | "done";

const POLL_MS = 2000;
const DONE_SHOW_MS = 4000;
const POS_KEY = "robot-assistant-pos";
const ROBOT_W = 96;
const ROBOT_H = 120;
// Below this much total pointer travel (px), a pointerdown->pointerup is
// treated as a click (opens/closes the chat) rather than a drag.
const CLICK_MOVE_THRESHOLD = 6;

interface ChatMessage {
  id: string;
  role: "user" | "ai";
  content: string;
}

function clampToViewport(x: number, y: number) {
  const maxX = Math.max(0, window.innerWidth - ROBOT_W);
  const maxY = Math.max(0, window.innerHeight - ROBOT_H);
  return { x: Math.min(Math.max(0, x), maxX), y: Math.min(Math.max(0, y), maxY) };
}

// One-time welcome tour text, shown as a synthetic (never persisted to the
// server) leading message the first time a signed-in user opens the chat —
// see the tourSeenKey/firstRunTimerRef logic below. Kept in sync by hand
// with HeaderBar.tsx's navItems; not generated by the AI so the very first
// thing a new user reads is guaranteed accurate.
const WELCOME_ZH = `你好！我是 COTORX 的小助手 👋 先带你快速认识一下这个网站：

📹 **Video Analysis（首页）** — 粘贴任意 TikTok 视频链接，AI 会拆解它的开场钩子、6 段式结构（Reaction/Hook/痛点/产品介绍/期望结果/CTA）和带货话术技巧，还能据此为你自己的产品生成新脚本。

📈 **Trends** — 按类目扫描当下 TikTok Shop 正在爆的视频和商品，找灵感用的。

🧑‍💼 **Creator Tracker** — 追踪达人/联盟主播的历史表现、GPM、互动率等，帮你判断值不值得合作。

🎬 **Creation** — 从零开始的创作画布：拖拽卡片规划分镜、写脚本、加拍摄指南，支持上传素材/AI生成图/粘贴TikTok链接导入，卡片连线后能一键生成整支视频，画布顶部还有一个日记聊天框，AI会陪你聊天并悄悄记录你的习惯偏好。

有任何关于怎么用的问题，随时在这里问我！`;

const WELCOME_EN = `Hey! I'm your COTORX assistant 👋 Quick tour of the site:

📹 **Video Analysis (home)** — paste any TikTok link and I'll break down its hook, 6-stage structure (Reaction/Hook/Pain Point/Product Intro/Desired Outcome/CTA), and selling-point techniques — then generate a new script for your own product from it.

📈 **Trends** — scans what's currently trending on TikTok Shop by category, for inspiration.

🧑‍💼 **Creator Tracker** — tracks creators/affiliates' performance over time so you can judge who's worth partnering with.

🎬 **Creation** — a from-scratch storyboard canvas: drag cards to plan shots, write scripts, attach a Shooting Guide, upload/AI-generate/import clips, connect cards into a sequence and render a video. There's also a docked Journal chat at the top that gets to know your habits/preferences over time.

Ask me anything about how to use the site, anytime!`;

export default function RobotAssistant({
  loggedIn = false,
  userId = null,
}: {
  loggedIn?: boolean;
  userId?: string | null;
}) {
  const { locale } = useLocale();
  const pathname = usePathname();
  const [mood, setMood] = useState<Mood>("idle");
  const [pos, setPos] = useState<{ x: number; y: number } | null>(null);
  const [dragging, setDragging] = useState(false);

  // ---- chat panel ----
  const [chatOpen, setChatOpen] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [historyLoaded, setHistoryLoaded] = useState(false);
  const [showWelcome, setShowWelcome] = useState(false);
  const [draft, setDraft] = useState("");
  const [sending, setSending] = useState(false);
  const [chatError, setChatError] = useState<string | null>(null);
  const chatScrollRef = useRef<HTMLDivElement>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const prevActiveRef = useRef(0);
  const doneTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const dragOffsetRef = useRef({ dx: 0, dy: 0 });
  const gestureStartRef = useRef({ x: 0, y: 0 });
  const gestureMovedRef = useRef(0);

  // Initial position: bottom-right, or wherever it was last dragged to.
  useEffect(() => {
    let saved: { x: number; y: number } | null = null;
    try {
      const raw = localStorage.getItem(POS_KEY);
      if (raw) saved = JSON.parse(raw);
    } catch {
      /* ignore corrupt storage */
    }
    const fallback = { x: window.innerWidth - ROBOT_W - 24, y: window.innerHeight - ROBOT_H - 24 };
    const p = saved && typeof saved.x === "number" && typeof saved.y === "number" ? saved : fallback;
    setPos(clampToViewport(p.x, p.y));

    const onResize = () => setPos((cur) => (cur ? clampToViewport(cur.x, cur.y) : cur));
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  // Poll the server for in-flight Claude work.
  useEffect(() => {
    let stopped = false;

    const tick = async () => {
      if (document.visibilityState === "hidden") return;
      try {
        const res = await fetch("/api/ai-activity", { cache: "no-store" });
        if (!res.ok) return; // e.g. 401 on the login page — stay idle
        const data = (await res.json()) as { active: number };
        if (stopped) return;

        const wasActive = prevActiveRef.current;
        prevActiveRef.current = data.active;

        if (data.active > 0) {
          if (doneTimerRef.current) {
            clearTimeout(doneTimerRef.current);
            doneTimerRef.current = null;
          }
          setMood("working");
        } else if (wasActive > 0) {
          setMood("done");
          doneTimerRef.current = setTimeout(() => setMood("idle"), DONE_SHOW_MS);
        }
      } catch {
        /* network hiccup — keep current mood */
      }
    };

    tick();
    const id = setInterval(tick, POLL_MS);
    return () => {
      stopped = true;
      clearInterval(id);
      if (doneTimerRef.current) clearTimeout(doneTimerRef.current);
    };
  }, []);

  // ---- click-to-chat vs. drag-to-move ----
  // Loads the persisted history the first time the panel opens; the
  // scripted welcome tour (see the first-run effect below) is layered on
  // top as a synthetic, never-persisted leading bubble rather than mixed
  // into this array.
  const loadHistory = useCallback(() => {
    if (historyLoaded) return;
    setHistoryLoaded(true);
    fetch("/api/assistant", { cache: "no-store" })
      .then((r) => r.json())
      .then((data) => {
        const loaded: ChatMessage[] = (data.messages || []).map((m: any) => ({ id: m.id, role: m.role, content: m.content }));
        setMessages(loaded);
      })
      .catch(() => {
        /* chat still usable without history — new messages just won't have prior context in the UI */
      });
  }, [historyLoaded]);

  function toggleChat() {
    if (!loggedIn) return;
    setChatOpen((open) => {
      const next = !open;
      if (next) loadHistory();
      return next;
    });
  }

  async function sendChatMessage() {
    const text = draft.trim();
    if (!text || sending) return;
    setDraft("");
    setChatError(null);
    setMessages((prev) => [...prev, { id: crypto.randomUUID(), role: "user", content: text }]);
    setSending(true);
    try {
      const res = await fetch("/api/assistant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: text }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to get a reply");
      setMessages((prev) => [...prev, { id: data.message.id, role: "ai", content: data.message.content }]);
    } catch (err: any) {
      setChatError(err.message || "Failed to get a reply");
    } finally {
      setSending(false);
    }
  }

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ block: "end" });
  }, [messages, sending, chatOpen]);

  // ---- first-run welcome tour ----
  // The very first time a signed-in user has this component mounted (per
  // browser, keyed by userId so switching accounts on the same machine
  // re-triggers it), auto-open the chat with the scripted welcome text
  // instead of waiting for a click. Fires once, shortly after mount so it
  // doesn't compete with the page's own initial layout/animations.
  useEffect(() => {
    if (!loggedIn || !userId) return;
    const key = `cotorx-tour-seen-${userId}`;
    let seen = true;
    try {
      seen = localStorage.getItem(key) === "1";
    } catch {
      seen = true; // storage unavailable — don't risk repeating the tour every load
    }
    if (seen) return;
    const timer = setTimeout(() => {
      try {
        localStorage.setItem(key, "1");
      } catch {
        /* storage unavailable — tour just won't be remembered, harmless */
      }
      setShowWelcome(true);
      setChatOpen(true);
      loadHistory();
    }, 900);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loggedIn, userId]);

  const onPointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if (!pos) return;
      e.preventDefault();
      try {
        (e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId);
      } catch {
        /* synthetic/stale pointer — dragging still works via bubbled moves */
      }
      dragOffsetRef.current = { dx: e.clientX - pos.x, dy: e.clientY - pos.y };
      gestureStartRef.current = { x: e.clientX, y: e.clientY };
      gestureMovedRef.current = 0;
      setDragging(true);
    },
    [pos]
  );

  const onPointerMove = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if (!dragging) return;
      const { x, y } = gestureStartRef.current;
      gestureMovedRef.current = Math.max(gestureMovedRef.current, Math.abs(e.clientX - x) + Math.abs(e.clientY - y));
      const { dx, dy } = dragOffsetRef.current;
      setPos(clampToViewport(e.clientX - dx, e.clientY - dy));
    },
    [dragging]
  );

  const onPointerUp = useCallback(
    (e: React.PointerEvent<HTMLDivElement>) => {
      if (!dragging) return;
      try {
        (e.currentTarget as HTMLDivElement).releasePointerCapture(e.pointerId);
      } catch {
        /* capture may not have been acquired */
      }
      setDragging(false);
      const wasClick = gestureMovedRef.current < CLICK_MOVE_THRESHOLD;
      setPos((cur) => {
        if (cur) {
          try {
            localStorage.setItem(POS_KEY, JSON.stringify(cur));
          } catch {
            /* storage unavailable */
          }
        }
        return cur;
      });
      if (wasClick) toggleChat();
    },
    [dragging]
  );

  if (!pos || pathname === "/login" || pathname === "/register" || pathname === "/onboarding") return null;

  const bubbleText = mood === "working" ? "Working" : mood === "done" ? "Done!" : null;

  return (
    <>
    <div
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      style={{
        position: "fixed",
        left: pos.x,
        top: pos.y,
        width: ROBOT_W,
        zIndex: 9999,
        cursor: dragging ? "grabbing" : "grab",
        touchAction: "none",
        userSelect: "none",
      }}
      aria-label="AI assistant robot — click to chat, drag to move"
      title={loggedIn ? "Click to chat · drag to move" : "Drag me anywhere"}
    >
      <style>{`
        @keyframes robot-bob {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-5px); }
        }
        @keyframes robot-shake {
          0%, 100% { transform: translateY(0) rotate(0deg); }
          25% { transform: translateY(-2px) rotate(-2deg); }
          75% { transform: translateY(-2px) rotate(2deg); }
        }
        @keyframes robot-antenna-blink {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.25; }
        }
        @keyframes robot-eye-scan {
          0%, 100% { transform: translateX(0); }
          30% { transform: translateX(-4px); }
          70% { transform: translateX(4px); }
        }
        @keyframes robot-blink {
          0%, 92%, 100% { transform: scaleY(1); }
          95% { transform: scaleY(0.1); }
        }
        @keyframes robot-dots {
          0% { content: ""; }
        }
        @keyframes robot-dot-pulse {
          0%, 80%, 100% { opacity: 0.2; }
          40% { opacity: 1; }
        }
        @keyframes robot-bubble-pop {
          0% { transform: scale(0.6); opacity: 0; }
          100% { transform: scale(1); opacity: 1; }
        }
        @keyframes robot-chat-badge-pulse {
          0%, 100% { transform: scale(1); box-shadow: 0 0 0 0 rgba(14,165,233,0.55); }
          50% { transform: scale(1.08); box-shadow: 0 0 0 5px rgba(14,165,233,0); }
        }
      `}</style>

      {/* Speech bubble */}
      {bubbleText && (
        <div
          style={{
            position: "absolute",
            bottom: ROBOT_H - 8,
            left: "50%",
            transform: "translateX(-50%)",
            background: mood === "done" ? "#22c55e" : "#0ea5e9",
            color: "white",
            fontSize: 12,
            fontWeight: 700,
            padding: "4px 10px",
            borderRadius: 12,
            whiteSpace: "nowrap",
            boxShadow: "0 4px 12px rgba(0,0,0,0.35)",
            animation: "robot-bubble-pop 0.25s ease-out",
            display: "flex",
            alignItems: "center",
            gap: 2,
          }}
        >
          {bubbleText}
          {mood === "working" && (
            <span style={{ display: "inline-flex", gap: 2, marginLeft: 2 }}>
              {[0, 1, 2].map((i) => (
                <span
                  key={i}
                  style={{
                    width: 3,
                    height: 3,
                    borderRadius: "50%",
                    background: "white",
                    animation: `robot-dot-pulse 1.2s ${i * 0.2}s infinite`,
                  }}
                />
              ))}
            </span>
          )}
        </div>
      )}

      {/* Robot body */}
      <div
        style={{
          position: "relative",
          animation: dragging
            ? "none"
            : mood === "working"
            ? "robot-shake 0.8s ease-in-out infinite"
            : "robot-bob 3s ease-in-out infinite",
          filter: "drop-shadow(0 6px 10px rgba(0,0,0,0.35))",
        }}
      >
        <svg viewBox="0 0 96 120" width={ROBOT_W} height={ROBOT_H}>
          {/* Antenna */}
          <line x1="48" y1="14" x2="48" y2="26" stroke="#93c5fd" strokeWidth="3" strokeLinecap="round" />
          <circle
            cx="48"
            cy="10"
            r="6"
            fill={mood === "working" ? "#f97316" : "#fb923c"}
            style={{ animation: mood === "working" ? "robot-antenna-blink 0.6s infinite" : "none" }}
          />

          {/* Ears */}
          <rect x="2" y="44" width="10" height="22" rx="5" fill="#60a5fa" />
          <rect x="84" y="44" width="10" height="22" rx="5" fill="#60a5fa" />

          {/* Head */}
          <rect x="10" y="24" width="76" height="62" rx="20" fill="#e8f4fb" stroke="#bfdbfe" strokeWidth="2" />

          {/* Face screen */}
          <rect x="20" y="34" width="56" height="42" rx="14" fill="#0f2137" />

          {/* Eyes */}
          {mood === "done" ? (
            // happy ^_^ eyes
            <g stroke="#67e8f9" strokeWidth="4" strokeLinecap="round" fill="none">
              <path d="M31 56 q5 -8 10 0" />
              <path d="M55 56 q5 -8 10 0" />
            </g>
          ) : (
            <g
              style={{
                animation: mood === "working" ? "robot-eye-scan 1.6s ease-in-out infinite" : "none",
              }}
            >
              <g style={{ animation: mood === "idle" ? "robot-blink 4s infinite" : "none", transformOrigin: "48px 54px" }}>
                <rect x="30" y="46" width="12" height="16" rx="6" fill="#67e8f9" />
                <rect x="54" y="46" width="12" height="16" rx="6" fill="#67e8f9" />
              </g>
            </g>
          )}

          {/* Mouth */}
          <path
            d={mood === "done" ? "M40 66 q8 8 16 0" : "M42 67 q6 5 12 0"}
            stroke="#67e8f9"
            strokeWidth="3"
            strokeLinecap="round"
            fill="none"
          />

          {/* Body */}
          <rect x="26" y="88" width="44" height="26" rx="12" fill="#dceefb" stroke="#bfdbfe" strokeWidth="2" />
          <circle cx="48" cy="101" r="6" fill={mood === "working" ? "#f97316" : "#93c5fd"} style={{ animation: mood === "working" ? "robot-antenna-blink 0.9s infinite" : "none" }} />

          {/* Arms */}
          <rect x="14" y="92" width="10" height="18" rx="5" fill="#93c5fd" transform={mood === "working" ? "rotate(-15 19 101)" : undefined} />
          <rect x="72" y="92" width="10" height="18" rx="5" fill="#93c5fd" transform={mood === "working" ? "rotate(15 77 101)" : undefined} />
        </svg>

        {/* Chat affordance badge — a small pulsing bubble hinting the robot
            is clickable, hidden once the chat's actually been opened at
            least once this session so it doesn't nag forever. */}
        {loggedIn && !chatOpen && (
          <div
            style={{
              position: "absolute",
              right: 2,
              bottom: 14,
              width: 22,
              height: 22,
              borderRadius: "50%",
              background: "#0ea5e9",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontSize: 12,
              boxShadow: "0 2px 6px rgba(0,0,0,0.3)",
              animation: "robot-chat-badge-pulse 2.4s ease-in-out infinite",
              pointerEvents: "none",
            }}
          >
            💬
          </div>
        )}
      </div>
    </div>

    {/* Chat panel — pinned bottom-right independent of the robot's dragged
        position (the robot can be dragged anywhere; the panel staying put
        avoids it ever landing off-screen). */}
    {chatOpen && (
      <div
        style={{
          position: "fixed",
          right: 24,
          bottom: 24,
          width: 340,
          maxWidth: "calc(100vw - 32px)",
          height: 440,
          maxHeight: "calc(100vh - 48px)",
          zIndex: 10000,
          background: "#ffffff",
          borderRadius: 16,
          boxShadow: "0 12px 40px rgba(0,0,0,0.35)",
          border: "1px solid #e4e4e7",
          display: "flex",
          flexDirection: "column",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            padding: "10px 12px",
            background: "linear-gradient(135deg,#0ea5e9,#38bdf8)",
            color: "white",
            fontSize: 13,
            fontWeight: 700,
          }}
        >
          <span style={{ fontSize: 16 }}>🤖</span>
          <span style={{ flex: 1 }}>COTORX Assistant</span>
          <button
            onClick={() => setChatOpen(false)}
            aria-label="Close chat"
            style={{ background: "transparent", border: "none", color: "white", fontSize: 16, cursor: "pointer", lineHeight: 1, padding: 4 }}
          >
            ✕
          </button>
        </div>

        <div ref={chatScrollRef} style={{ flex: 1, minHeight: 0, overflowY: "auto", padding: "10px 12px", display: "flex", flexDirection: "column", gap: 8 }}>
          {showWelcome && (
            <div
              style={{
                alignSelf: "flex-start",
                maxWidth: "90%",
                background: "#f0f9ff",
                border: "1px solid #bae6fd",
                borderRadius: 12,
                padding: "8px 10px",
                fontSize: 12.5,
                lineHeight: 1.5,
                color: "#0c4a6e",
                whiteSpace: "pre-wrap",
              }}
            >
              {locale === "zh" ? WELCOME_ZH : WELCOME_EN}
            </div>
          )}
          {messages.length === 0 && !showWelcome && (
            <p style={{ fontSize: 12, color: "#71717a" }}>
              {locale === "zh" ? "问我任何关于网站功能怎么用的问题～" : "Ask me anything about how to use the site."}
            </p>
          )}
          {messages.map((m) => (
            <div
              key={m.id}
              style={{
                alignSelf: m.role === "user" ? "flex-end" : "flex-start",
                maxWidth: "88%",
                background: m.role === "user" ? "#0ea5e9" : "#f4f4f5",
                color: m.role === "user" ? "white" : "#27272a",
                borderRadius: 12,
                padding: "8px 10px",
                fontSize: 12.5,
                lineHeight: 1.5,
                whiteSpace: "pre-wrap",
              }}
            >
              {m.content}
            </div>
          ))}
          {sending && (
            <div style={{ alignSelf: "flex-start", fontSize: 12, color: "#a1a1aa" }} className="animate-pulse">
              ...
            </div>
          )}
          {chatError && <p style={{ fontSize: 11, color: "#ef4444" }}>{chatError}</p>}
          <div ref={messagesEndRef} />
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            sendChatMessage();
          }}
          style={{ display: "flex", gap: 6, padding: 10, borderTop: "1px solid #e4e4e7" }}
        >
          <input
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder={locale === "zh" ? "输入你的问题..." : "Ask a question..."}
            style={{
              flex: 1,
              minWidth: 0,
              padding: "7px 10px",
              borderRadius: 999,
              border: "1px solid #e4e4e7",
              fontSize: 12.5,
              outline: "none",
            }}
          />
          <button
            type="submit"
            disabled={!draft.trim() || sending}
            style={{
              padding: "7px 14px",
              borderRadius: 999,
              border: "none",
              background: !draft.trim() || sending ? "#93c5fd" : "#0ea5e9",
              color: "white",
              fontSize: 12.5,
              fontWeight: 600,
              cursor: !draft.trim() || sending ? "not-allowed" : "pointer",
            }}
          >
            {locale === "zh" ? "发送" : "Send"}
          </button>
        </form>
      </div>
    )}
    </>
  );
}
